FROM node:20-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN npm install -g pnpm@9.0.0

COPY . .

RUN pnpm install

RUN cd packages/db && npx prisma generate

RUN pnpm run build

EXPOSE 3001

WORKDIR /app/apps/http-backend
CMD ["pnpm", "run", "start"]