FROM node:22-alpine

WORKDIR /app

RUN npm install -g pnpm@9.0.0

COPY . .

RUN pnpm install --frozen-lockfile

RUN pnpm --filter @repo/db exec npx prisma generate

ARG NEXT_PUBLIC_HTTP_BACKEND=http://localhost:3001
ARG NEXT_PUBLIC_WS_URL=ws://localhost:8080
ENV NEXT_PUBLIC_HTTP_BACKEND=$NEXT_PUBLIC_HTTP_BACKEND
ENV NEXT_PUBLIC_WS_URL=$NEXT_PUBLIC_WS_URL

RUN pnpm run build

EXPOSE 3000

WORKDIR /app/apps/frontend
CMD ["pnpm", "run", "start"]
